/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : bigint,
  'title' : string,
  'destination' : string,
  'content' : string,
  'publishedBy' : Principal,
  'timestamp' : Time,
  'image' : [] | [ExternalBlob],
}
export type ExternalBlob = Uint8Array;
export interface GuideProfile {
  'bio' : string,
  'name' : string,
  'role' : string,
  'photo' : [] | [ExternalBlob],
}
export interface Inquiry {
  'id' : bigint,
  'name' : string,
  'travelDates' : string,
  'email' : string,
  'tourType' : TourType,
  'message' : string,
  'timestamp' : Time,
  'phone' : string,
}
export interface Package {
  'duration' : string,
  'name' : string,
  'description' : string,
  'destinations' : Array<string>,
  'price' : bigint,
}
export type Time = bigint;
export type TourType = { 'dhakaCity' : null } |
  { 'sundarbans' : null } |
  { 'coxBazar' : null } |
  { 'bandarban' : null } |
  { 'sajekValley' : null };
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addGuideProfile' : ActorMethod<
    [string, string, string, [] | [ExternalBlob]],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBlogPost' : ActorMethod<
    [string, string, string, [] | [ExternalBlob]],
    bigint
  >,
  'deleteBlogPost' : ActorMethod<[bigint], undefined>,
  'getAllBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getAllGuideProfiles' : ActorMethod<[], Array<GuideProfile>>,
  'getAllInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getAllPackages' : ActorMethod<[], Array<Package>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitInquiry' : ActorMethod<
    [string, string, string, TourType, string, string],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];